### ISSUE TITLE
Would like to configure conprof to run in a different URL

### ISSUE THREAD

**Issue by bboreham** [conprof/conprof#152]
I would like to proxy conprof, so that the URL on the outside is like `http://example.com/conprof`.

Can we add something like Prometheus `--web.external-url` flag?

#39 was closed, and the UI now paints, but if I try to run a query it makes a request like `/api/v1/query_range?from=1614161843691&to=1614165535095&query=%7Bjob%3D%22foo%22%7D` to the root of the webserver.

**Comment by brancz** [comment]
Yeah, I think we should allow running under a path. I'm not sure I necessarily like Prometheus external url approach, if we could just have our frontend do requests from the "root" + api path, I think that would be my preferred option. What do you think?

**Comment by brancz** [comment]
Turns out that's exactly what the new Prometheus react UI does as well: https://github.com/prometheus/prometheus/blob/7bf76af6dffc020fb7c4d489694bb8db0a223add/web/ui/react-app/src/contexts/PathPrefixContext.tsx#L5

**Comment by brancz** [comment]
I don't have an environment like what you're looking for, but I believe #154 should do the trick if you also deploy conprof with a reverse proxy that removes the prefix. Would you be able to try that with the latest build?

**Comment by bboreham** [comment]
Very close; now it requests `http://example.com/conprof//api/v1/query_range?from=...`, and only the double-slash prevents it from working.

**Comment by brancz** [comment]
@bboreham do you mind trying the latest build, I believe that should be fixed now! :)

**Comment by bboreham** [comment]
That one is fixed!

Now the UI paints after a query, but clicking on an individual blob goes to `http://example.com/pprof/longhashstring` not `http://example.com/conprof/pprof/longhashstring`

**Comment by brancz** [comment]
Of course.. :D 

I'll fix that one as well.

**Comment by brancz** [comment]
Merged #157, which should fix that one as well. Let me know how it goes!

**Comment by bboreham** [comment]
Working now; thanks!

**Comment by brancz** [comment]
Awesome! Let us know if you have a story to share, if conprof helped you! Also happy to give you access to the Polar Signals Continuous Profiler product if you would like to try it!
