### ISSUE TITLE
How to deploy for HA?

### ISSUE THREAD

**Issue by vision9527** [conprof/conprof#163]
Hello, bro.
I want to start the cluster for HA, How I should do?

**Comment by brancz** [comment]
When you say HA, do you have something specific in mind?

Profiling doesn't really allow collecting twice at the same time, so it can't be done on the collection level. What point of failure are you trying to prevent?

**Comment by vision9527** [comment]
> When you say HA, do you have something specific in mind?
> 
> Profiling doesn't really allow collecting twice at the same time, so it can't be done on the collection level. What point of failure are you trying to prevent?

I want to prevent some collection from crashing.
