### ISSUE TITLE
Rust memory profiler future source candidate: koute/memory-profiler

### ISSUE THREAD

**Issue by bbros-dev** [conprof/conprof#166]
Not sure if this is a candidate for memory profiling in Rust:

https://github.com/koute/memory-profiler

> - Gathers every allocation and deallocation, along with full stack traces
> ...
> - Can dynamically stream the profiling data to another machine instead of saving it locally, which is useful for profiling on memory-constrained systems

Output is currently in JSON and Heaptrack formats so would need a new format. Not sure what else?

**Comment by brancz** [comment]
It looks like it largely works based on `perf` events. This is something we've been wanting to look into for some time, as I agree this is a really great idea for a "generic" profiler. That said, anything like `perf` or ebpf, won't be able to deliver line-number style statistics. For rust, it seems that [`pprof-rs`](https://github.com/tikv/pprof-rs) is actually looking to implement memory profiling: https://github.com/tikv/pprof-rs/pull/45. It looks like it's pretty far but the author doesn't have time to finish it up right now it seems. If there are any rust experts around (maybe you!) this would be really amazing to have in pprof-rs indeed!

**Comment by bbros-dev** [comment]
Closing as it seems the effort is undereau appropriate place is https://github.com/tikv/pprof-rs/pull/45
