### ISSUE TITLE
Support collecting profiles from short-lived jobs

### ISSUE THREAD

**Issue by yeya24** [conprof/conprof#175]
Hi, I have some use cases about collecting profiles from short-lived jobs and querying these profiles from the conprof TSDB. For example, profiles collected from go benchmarks. 

@brancz mentioned that this can be achieved with the existing profile gRPC client to write the profiles to the remote store.

So I propose to add this feature to the conprof sampler or another separate `conprof xxx` subcommand. This should read a profile from a file, attach specified label sets and send a request to the store.

**Comment by brancz** [comment]
I think we should expose the gRPC store API in the `all` command just like it is in the `api` command, then we could add a `--one-off` flag to the sampler (or an entirely new subcommand?) that sends the profile to the backend. Wdyt?

cc @thorfour as we wanted to expose the store API on the `all` subcommand for other reasons.

**Comment by thorfour** [comment]
https://github.com/conprof/conprof/pull/176 should address this by allowing grpc writes directly to conprof

**Comment by thorfour** [comment]
As #176 is merged now, I'm marking this issue as closed, as the ability to support collecting profiles from short lived job should be supported.

**Comment by brancz** [comment]
I tend to agree with @yeya24, basically we are still missing a utility that allows us to send a pprof file from disk to a backend.
