### ISSUE TITLE
Config is in a secret

### ISSUE THREAD

**Issue by bboreham** [conprof/conprof#32]
Referring to this file: https://github.com/conprof/conprof/blob/master/deployments/manifests/configsecret.yaml

There's nothing secret there, nor is base64 a particularly hard cypher.

Wouldn't it be easier to put it in a ConfigMap?

**Comment by ant31** [comment]
Well the base64 is a kubernetes thing, let's not debate that. 

About configmap or secret, I think the pull configuration can include the HTTP AUTH information, which should be secret.

**Comment by bboreham** [comment]
OK, fair point.  Perhaps that auth information could be indirected so the main config is readable.

**Comment by brancz** [comment]
I believe one can use `stringData` instead of `data` and provide a string instead of base64 encoded data? I'd be happy with that change.

**Comment by brancz** [comment]
Moved the configuration to a `stringData` field in the `Secret`. Hopefully that resolves the concern: https://github.com/conprof/conprof/blob/bb3d279fb1a8b7162438c4bbc462d0aba1ca8fff/deployments/manifests/secret.yaml#L11-L35

**Comment by metalmatze** [comment]
Due to no objections I'd mark this as resolved for now.
