### ISSUE TITLE
How do I configure conprof to run in a different URL

### ISSUE THREAD

**Issue by bboreham** [conprof/conprof#39]
I would like to proxy conprof, so that the URL on the outside is like http://example.com/conprof.

Is there something like Prometheus `--web.external-url` flag?

**Comment by brancz** [comment]
I was under the assumption that the single page app front end would just work, but I might have used non relative paths. I don’t think something like external url/pathprefix is necessary in conprof, but I might very well be the case that I made a mistake that prevents this today.

**Comment by bboreham** [comment]
My browser "view source" shows the following absolute urls:

```
...
<link href="/static/css/2.740a17b8.chunk.css" rel="stylesheet"></head>
<body>
...
<script src="/static/js/2.50b5a495.chunk.js"></script>
<script src="/static/js/main.66194267.chunk.js"></script>
</body>
```

**Comment by brancz** [comment]
Aha! Yes that seems like the culprit. Happy to accept the change to make it relative.

**Comment by bboreham** [comment]
I couldn't figure out what causes it.  For instance `chunk` does not appear in this repo.
I don't really do front-end.

**Comment by geobeau** [comment]
Late to the party but it's due to the `react-scripts build` which assume that it's built to run on / 
See the build message:
```> react-scripts build

Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Compiled successfully.

File sizes after gzip:

  222.53 KB  build/static/js/2.50b5a495.chunk.js
  3.02 KB    build/static/js/main.c537a319.chunk.js
  762 B      build/static/js/runtime~main.a8a9905a.js
  580 B      build/static/css/2.d1aa2739.chunk.css

The project was built assuming it is hosted at the server root.
You can control this with the homepage field in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  https://bit.ly/CRA-deploy```

There is the instructions if you want to build it for your specific path (you will need to build the UI by following the instructions of the README)

**Comment by brancz** [comment]
Is it also possible to build it in a way that make this relative?

**Comment by geobeau** [comment]
I made an attempt to fix it in the linked PR. I had to change the router to work with any path. When there will be more pages, it will need to be adapted (and I'm not sure how)
