### ISSUE TITLE
some profiles fail scraping

### ISSUE THREAD

**Issue by povilasv** [conprof/conprof#46]
```
conprof-0 conprof level=debug ts=2020-04-28T04:21:13.165040571Z caller=scrape.go:370 component=scrape-manager scrape_pool=conprof msg="scraping profile" url=http://10.200.2.38:8080/debug/pprof/trace
conprof-0 conprof level=debug ts=2020-04-28T04:21:14.18123509Z caller=scrape.go:505 component=scrape-manager scrape_pool=conprof target=http://10.200.2.38:8080/debug/pprof/trace msg="Scrape failed" err="failed to parse target's pprof profile: parsing profile: unrecognized profile format"
```

Same for cmdline profile:
```
conprof-0 conprof level=debug ts=2020-04-28T04:23:02.305811774Z caller=scrape.go:370 component=scrape-manager scrape_pool=conprof msg="scraping profile" url=http://10.200.0.177:8080/debug/pprof/cmdline
conprof-0 conprof level=debug ts=2020-04-28T04:23:02.310718078Z caller=scrape.go:505 component=scrape-manager scrape_pool=conprof target=http://10.200.0.177:8080/debug/pprof/cmdline msg="Scrape failed" err="failed to parse target's pprof profile: parsing profile: unrecognized profile format"
```

Might be a consequence of running on arm

**Comment by brancz** [comment]
I assume subsequent scrapes are working?

**Comment by povilasv** [comment]
Nope, all of them fail 

I'm currently just collecting pprof's from conprof
```
rl=http://10.200.0.177:8080/debug/pprof/cmdline
level=debug ts=2020-04-28T14:50:02.307342886Z caller=scrape.go:505 component=scrape-manager scrape_pool=conprof target=http://10.200.0.177:8080/debug/pprof/cmdline msg="Scrape failed" err="failed to parse target's pprof profile: parsing profile: unrecognized profile format"
level=debug ts=2020-04-28T14:50:03.419355382Z caller=scrape.go:370 component=scrape-manager scrape_pool=conprof msg="scraping profile" url=http://10.200.0.177:8080/debug/pprof/mutex
level=debug ts=2020-04-28T14:50:03.927836756Z caller=scrape.go:370 component=scrape-manager scrape_pool=conprof msg="scraping profile" url=http://10.200.0.177:8080/debug/pprof/threadcreate
level=debug ts=2020-04-28T14:50:04.271020553Z caller=scrape.go:370 component=scrape-manager scrape_pool=conprof msg="scraping profile" url=http://10.200.2.38:8080/debug/pprof/profile
level=debug ts=2020-04-28T14:50:13.165194934Z caller=scrape.go:370 component=scrape-manager scrape_pool=conprof msg="scraping profile" url=http://10.200.2.38:8080/debug/pprof/trace
level=debug ts=2020-04-28T14:50:14.171548533Z caller=scrape.go:505 component=scrape-manager scrape_pool=conprof target=http://10.200.2.38:8080/debug/pprof/trace msg="Scrape failed" err="failed to parse target's pprof profile: parsing profile: unrecognized profile format"
```

**Comment by povilasv** [comment]
This is the contents of `http://localhost:8080/debug/pprof/cmdline` from conprof pod:

[cmdline.txt](https://github.com/conprof/conprof/files/4546539/cmdline.txt)

**Comment by syepes** [comment]
I have also just build the project from master and it not able to scrap itself nor any of my projects built with 1.14.2

Is there currently an issue/fix for this?

```
level=debug ts=2020-04-28T22:23:29.358497874Z caller=scrape.go:505 component=scrape-manager scrape_pool=conprof target=http://localhost:8080/debug/pprof/trace msg="Scrape failed" err=
"failed to parse target's pprof profile: parsing profile: unrecognized profile format"
level=debug ts=2020-04-28T22:23:31.105672907Z caller=scrape.go:370 component=scrape-manager scrape_pool=conprof msg="scraping profile" url=http://localhost:8080/debug/pprof/block
level=debug ts=2020-04-28T22:23:31.309165448Z caller=scrape.go:370 component=scrape-manager scrape_pool=conprof msg="scraping profile" url=http://localhost:8080/debug/pprof/allocs
level=debug ts=2020-04-28T22:23:36.404392335Z caller=scrape.go:370 component=scrape-manager scrape_pool=conprof msg="scraping profile" url=http://localhost:8080/debug/pprof/profile
level=debug ts=2020-04-28T22:23:51.891763991Z caller=scrape.go:370 component=scrape-manager scrape_pool=conprof msg="scraping profile" url=http://localhost:8080/debug/pprof/goroutine
level=debug ts=2020-04-28T22:23:52.290836201Z caller=scrape.go:370 component=scrape-manager scrape_pool=conprof msg="scraping profile" url=http://localhost:8080/debug/pprof/cmdline
level=debug ts=2020-04-28T22:23:52.291465509Z caller=scrape.go:505 component=scrape-manager scrape_pool=conprof target=http://localhost:8080/debug/pprof/cmdline msg="Scrape failed" er
r="failed to parse target's pprof profile: parsing profile: unrecognized profile format"
level=debug ts=2020-04-28T22:24:15.571826594Z caller=scrape.go:370 component=scrape-manager scrape_pool=conprof msg="scraping profile" url=http://localhost:8080/debug/pprof/mutex
level=debug ts=2020-04-28T22:24:18.492315323Z caller=scrape.go:370 component=scrape-manager scrape_pool=conprof msg="scraping profile" url=http://localhost:8080/debug/pprof/heap
level=debug ts=2020-04-28T22:24:26.875040226Z caller=scrape.go:370 component=scrape-manager scrape_pool=conprof msg="scraping profile" url=http://localhost:8080/debug/pprof/threadcrea
te
level=debug ts=2020-04-28T22:24:28.357037155Z caller=scrape.go:370 component=scrape-manager scrape_pool=conprof msg="scraping profile" url=http://localhost:8080/debug/pprof/trace
level=debug ts=2020-04-28T22:24:29.358824086Z caller=scrape.go:505 component=scrape-manager scrape_pool=conprof target=http://localhost:8080/debug/pprof/trace msg="Scrape failed" err=
"failed to parse target's pprof profile: parsing profile: unrecognized profile format"
```

**Comment by povilasv** [comment]
So basically there is no support for traces in https://github.com/google/pprof/issues/529 and won't be.

There is a way to convert  traces to pprof using `go tool trace -pprof=TYPE trace.out > TYPE.pprof`.
Types:
```
- net: network blocking profile
- sync: synchronization blocking profile
- syscall: syscall blocking profile
- sched: scheduler latency profile
```

One option is to convert trace to pprof, which would mean roughly copy paste & adapt code https://golang.org/src/cmd/trace/pprof.go here.

Another option actually support golang traces and build UI on top of that? (The way go tool does it now).

Also question what we can do with cmdline?

**Comment by povilasv** [comment]
IMO supporting go tool trace is a better option as the go tool trace is quite useful:

![image](https://user-images.githubusercontent.com/22289110/80559952-e1fb1280-89e7-11ea-8a9a-a4fa733be3ce.png)

**Comment by syepes** [comment]
@povilasv 
Interesting, but did you get it working on any of the profiles? I have been actively spacing 4 apps and in the UI I don't see anything at all

![image](https://user-images.githubusercontent.com/333081/80566634-b847e880-89f3-11ea-8d44-86d6db8ff380.png)

**Comment by povilasv** [comment]
you need to add query expression, like `{job="conprof"}`, as the landing page doesn't show you anything without expression.

**Comment by brancz** [comment]
@povilasv both of those suggestions sound good to me (remove cmdline, embed trace UI).

**Comment by syepes** [comment]
@povilasv Thanks for the tip! it's now working :-)

**Comment by povilasv** [comment]
I've made some progress :man_dancing: 
![conprof_trace](https://user-images.githubusercontent.com/22289110/81490233-214b1e00-9288-11ea-8521-0e4d43954a80.gif)


My proposal to move this forward is:
1) We copy go's internal/trace package to internal/trace, leave the License headers as is.
2) We add a new `profile_type` label to all profiles. This is need to figure out which UI to show + new you can query for specific type of profile :)
3) We add a new `internal/traceui` package which roughly copies `/usr/lib/go/src/cmd/trace`, but instead of using global variable, which stores parsed profile we change it to actually take it as an argument.

Still needs some work:
1) Network blocking profile
2) Synchronization blocking profile
3) Syscall blocking profile
4) Scheduler latency profile

As internally go tool just converts them to pprof and outputs a svg. Maybe I can just use pprof UI instead.

My approach would be we add those internal packages to the repo incrementally and expose UIs to users little by little.

Thoughts?

**Comment by brancz** [comment]
I don't mind copying the internal code, I've started doing this on a branch as well which convert profile nodes into Prometheus remote read.

> We add a new internal/traceui package which roughly copies /usr/lib/go/src/cmd/trace, but instead of using global variable, which stores parsed profile we change it to actually take it as an argument.

I would say even if we copy the internal package, let's try contributing this upstream as we're going to want to stay as close to upstream as possible, making copying of internal essentially vendoring.

**Comment by povilasv** [comment]
> I don't mind copying the internal code, I've started doing this on a branch as well which convert profile nodes into Prometheus remote read.
> 
> > We add a new internal/traceui package which roughly copies /usr/lib/go/src/cmd/trace, but instead of using global variable, which stores parsed profile we change it to actually take it as an argument.
> 
> I would say even if we copy the internal package, let's try contributing this upstream as we're going to want to stay as close to upstream as possible, making copying of internal essentially vendoring.

Agree, I've created an issue https://github.com/golang/go/issues/38971 if Go maintainers agree, I would try to help them .

**Comment by povilasv** [comment]
BTW I actually made everything work :dancers: 

![conprof_demo](https://user-images.githubusercontent.com/22289110/81494378-296b8380-92b1-11ea-8f2f-14d71e742d4c.gif)

**Comment by brancz** [comment]
Nice! I don't even think it needs to necessarily be a non internal package, as long as we don't modify the "manually vendored" one.

**Comment by brancz** [comment]
In an attempt to not duplicate work, I opened a WIP for the remote read work I had laying around as that also did the internal manual vendoring: https://github.com/conprof/conprof/pull/54

**Comment by brancz** [comment]
Cycling back to the profile type proposal. I think something like type metadata in Prometheus would be more appropriate here. I think I'm ok with a stop gap (maybe analysing the profile scrape path) to heuristically decide what profile it _probably_ is (kind of like Prometheus interpreting `_bytes` metrics).

**Comment by povilasv** [comment]
What about users wanting to query for specific profiles? I can definitely see myself asking conprof "show me memory profiles for jobs conprof,traefik" . Right now we could only do it via paths.

 But what if my path is different for different types of apps? For example I can can easily configure HeapConfig job to scrape `/pprof/heap` for one application and  `/debug/heap` for another.

We already have specific types of config for each different profile, so it makes sense to me to have a type also.

For Prometheus it's a bit different as you have a metric name and you can query just that metric.

Thoughts?

**Comment by syepes** [comment]
IMHO, I kind of like the profile name / type solution as the queries won't change from app to app.

**Comment by brancz** [comment]
I think I like the ergonomics of the profile type/name being the entrypiont for querying. I think we're going to have to adjust the query language/API for this slightly.

**Comment by povilasv** [comment]
![image](https://user-images.githubusercontent.com/22289110/82108857-65cc3300-973a-11ea-85b8-92b4cc0e0d13.png)

managed to make it work :)

**Comment by povilasv** [comment]
As Add Profile Type got merged, we can now scrape traces, so closing this. I've opened a seperate issue for UI https://github.com/conprof/conprof/issues/61
