### ISSUE TITLE
Crash due to nil pointer dereference

### ISSUE THREAD

**Issue by schmidtw** [conprof/conprof#51]
I was able to trigger a crash by passing in a valid query that was no longer in the DB.

This line deferences the `s` value which could be `nil` from the line above.

https://github.com/conprof/conprof/blob/73bf4f064fdb3d36217f8ec10c523e932f4e95b0/pprofui/pprofui.go#L112

Reproduction Steps
1. Running conprof, getting a URL like this:
https://example.com/pprof/e19fYWRkcmVzc19fPSJsb2NhbGhvc3Q6ODA4MCIsX19zY2hlbWVfXz0iaHR0cCIsaW5zdGFuY2U9ImxvY2FsaG9zdDo4MDgwIixqb2I9ImNvbnByb2YiLHByb2ZpbGVfcGF0aD0iL2RlYnVnL3Bwcm9mL2FsbG9jcyJ9/1588343201278/
2. Stop conprof
3. Delete the db
4. Start conprof
5. Hit the url & watch the panic.

**Comment by brancz** [comment]
Should be fixed by #52 

Let us know if that does the trick for you! :)
