### ISSUE TITLE
Allow download pprof profiles for offline use

### ISSUE THREAD

**Issue by bwplotka** [conprof/conprof#64]

**Comment by brancz** [comment]
yes I've thought about this many times as well .. much like https://github.com/conprof/conprof/issues/65#issuecomment-655570542 I think this would be most convenient if it was part of the js frontend

**Comment by yeya24** [comment]
I have added a download link to the Pprof UI directly as we vendor that part of code already. Is this something that makes sense to add? Or it is better to add a download button in the conprof react UI?

![Screenshot from 2021-03-25 19-02-05](https://user-images.githubusercontent.com/25150124/112554419-a3f3a380-8d9c-11eb-85fa-0e603a4695a5.png)

**Comment by brancz** [comment]
Oh cool! No I think this is worth adding! I wonder how we can ensure that this stays though when the "manually vendored" code is updated?

**Comment by yeya24** [comment]
This change is not related to Conprof so I opened a pr to pprof https://github.com/google/pprof/pull/617 and I am not sure whether they will accept it or not.
We can fork that repo as well, what do you think?

**Comment by brancz** [comment]
I'm up for it either way. The PR you opened would of course be ideal, but I'm not opposed to adding it through the script either.

**Comment by sandangel** [comment]
@brancz it looks like my PR got approval. https://github.com/google/pprof/pull/634#pullrequestreview-672564067 ^^

**Comment by brancz** [comment]
Ooooooooo super cool!

**Comment by sandangel** [comment]
@brancz it's merged now. ^^
