### ISSUE TITLE
Reload config endpoint - /-/reload

### ISSUE THREAD

**Issue by syepes** [conprof/conprof#70]
It would be great to have the possibility to reload the configuration file, just like we can do with prometheus:

`curl -X POST http://localhost:8080/-/reload`

I see we have some methods, but it's not exposed:
https://github.com/conprof/conprof/blob/master/scrape/manager.go#L84

**Comment by brancz** [comment]
Agreed! If someone wants to pick this up that would be amazing!

**Comment by geobeau** [comment]
I can work on it if @syepes doesn't want!

**Comment by syepes** [comment]
@geobeau I had a rapid look last night but could not figure out how to add the hook, if your more familiar with the code base I'll also be interested in seeing how you implement it. :-)

**Comment by geobeau** [comment]
I made #71 which is a naive implementation. @brancz @syepes any advices on how to make it more elegant?

**Comment by brancz** [comment]
I merged #71, maybe @syepes can try out the image that will be built from master and we close this issue once tested? :)

**Comment by syepes** [comment]
I'll give this a try with your setup

**Comment by syepes** [comment]
@geobeau | @brancz 
I just have given this a test drive and there is an issue.

The reloading [gets triggered](https://github.com/conprof/conprof/blob/master/scrape/manager.go#L111) but it's reloading the current (old) config that was previously loaded on the struct, I think that before running the actual reload we need to call [ApplyConfig](https://github.com/conprof/conprof/blob/master/scrape/manager.go#L152) and then [updateTsets](https://github.com/conprof/conprof/blob/master/scrape/manager.go#L145) with the necessary parameters.

**Comment by brancz** [comment]
@geobeau do you think you could have a look at that?

**Comment by geobeau** [comment]
Yes, sorry for the issue

**Comment by geobeau** [comment]
Made another pull request. It looks like it's working fine now

**Comment by brancz** [comment]
Merged #70, @syepes can you retest with the latest build?

**Comment by syepes** [comment]
@geobeau  | @brancz 
Works like a charm! thanks
