### ISSUE TITLE
Bug: labels API and Series API not working

### ISSUE THREAD

**Issue by yeya24** [conprof/conprof#85]
```
curl localhost:10902/api/v1/labels
{"status":"success"}
```

Only status and no data returned. Seems this bug is caused by https://github.com/conprof/conprof/blob/master/api/api.go#L138. Need more investigation.

Assign myself. Will handing the response similar to Thanos https://github.com/thanos-io/thanos/blob/master/pkg/api/api.go#L219

**Comment by brancz** [comment]
Feel free to take this. @bwplotka mentioned a follow up would be good to contain tests as well :)

**Comment by bwplotka** [comment]
:+1:

**Comment by bwplotka** [comment]
Oh yea we forgot to marshal status lol ;p

**Comment by bwplotka** [comment]
Please help :+1:

**Comment by bwplotka** [comment]
and TESTS!
