### ISSUE TITLE
Getting duplicate series from query range API

### ISSUE THREAD

**Issue by yeya24** [conprof/conprof#95]
![Screenshot from 2020-10-15 11-41-05](https://user-images.githubusercontent.com/25150124/96153250-7c3e0c80-0edb-11eb-9180-b97e23fc4c3f.png)

I got duplicate series for heap{job="conprof"}. Should they be the same series?

**Comment by brancz** [comment]
hmm interesting, yes they should be

**Comment by brancz** [comment]
I believe this will be fixed by https://github.com/conprof/conprof/pull/113

**Comment by brancz** [comment]
Fixed by #113. Let me know if you still see this!
